### ISSUE TITLE
link logistic error rates

### ISSUE THREAD

**Issue by nikete** [ekg/hhga#14]
When using the logistic we get crazy high errors reported under --binary loss

for the plain linear model with logistic link and loss at 65536 :
0.378387  

while withoutany logistic:
0.013412    

while with only the loss logistic 
0.016068

are we fitting that badly or is it not the bianry loss that gets reported?

**Comment by ekg** [comment]
We might need to take this to vw chat or mailing list.

**Comment by nikete** [comment]
it is a reporting bug from vw
